-- ============================================================
-- schema.sql
-- ------------------------------------------------------------
-- ANPR Project Database Schema (MySQL)
--
-- What this script does:
-- 1) Creates database: anpr_db (if it does not exist)
-- 2) Creates core tables:
--    - owners   : demo owner information
--    - vehicles : vehicle mapped to owner (plate is primary key)
--    - fines    : fine logs generated by the ANPR pipeline
--
-- Ethics note:
-- This project uses DEMO / mock owner data stored locally.
-- No real personal data is used.
-- ============================================================


-- ------------------------------------------------------------
-- 1) Create and select database
-- ------------------------------------------------------------
CREATE DATABASE IF NOT EXISTS anpr_db;
USE anpr_db;


-- ------------------------------------------------------------
-- 2) owners table
--    Stores owner details (demo/mock data)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS owners (
  owner_id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL,
  phone VARCHAR(20),
  address VARCHAR(255)
);


-- ------------------------------------------------------------
-- 3) vehicles table
--    Stores vehicle details mapped to an owner
--
-- Notes:
-- - plate_number is PRIMARY KEY (unique identifier for a vehicle)
-- - owner_id is a FOREIGN KEY referencing owners(owner_id)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS vehicles (
  plate_number VARCHAR(20) PRIMARY KEY,
  owner_id INT NOT NULL,
  vehicle_type VARCHAR(50),
  FOREIGN KEY (owner_id) REFERENCES owners(owner_id)
);


-- ------------------------------------------------------------
-- 4) fines table
--    Stores logs for fines generated by the pipeline
--
-- Fields:
-- - plate_number   : vehicle plate number (FK -> vehicles.plate_number)
-- - violation_type : selected violation from UI dropdown
-- - fine_amount    : computed fine amount (INR)
-- - is_fined       : 1 if fine applied else 0
-- - ocr_text/conf  : OCR output + confidence (for debugging/metrics)
-- - created_at     : timestamp of log creation
-- - email_sent     : 0/1 flag (future step: update after email is sent)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fines (
  fine_id INT AUTO_INCREMENT PRIMARY KEY,
  plate_number VARCHAR(20) NOT NULL,
  violation_type VARCHAR(50) NOT NULL,
  fine_amount INT NOT NULL,
  is_fined TINYINT(1) NOT NULL,
  ocr_text VARCHAR(50),
  ocr_conf FLOAT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  email_sent TINYINT(1) DEFAULT 0,
  FOREIGN KEY (plate_number) REFERENCES vehicles(plate_number)
);

